### ISSUE TITLE
Piwo to-do list

### ISSUE THREAD

**Issue by ghaerdi** [crewdevio/Piwo#2]
## Features

- [ ] Colors for the body response output.
- [ ] Read a json file of scripts or something else with request instructions for Piwo.
- [ ] Send file support.
